version: '3.1'

Scheduler:
  mycontainer:
    image: myimage
    build: .
    volumes:
     #- './path/on/docker/host:/path/inside/container'
      
      - './:.usr/local/Airflow/'
      - './include/:.usr/local/Airflow/include'
      - './plugins/:.usr/local/Airflow/plugins'
      - './:.usr/local/Airflow/'